spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://localhost:4200"
            allowedMethods: GET, POST, PUT, DELETE
            allowedHeaders: '*'
            allowCredentials: true
            